#pragma once
#define COLLECTIBLE_DIM 8
#define BOMB_DIM 15
#define FOOD_DIM 5
#define MAP_WIDTH 21
#define MAP_HEIGHT 13
#define TILE_DIM 30
#define WINDOW_WIDTH (MAP_WIDTH * TILE_DIM + 200)
#define WINDOW_HEIGHT (MAP_HEIGHT * TILE_DIM)
