#pragma once
#define COLLECTIBLE_DIM 8
#define BOMB_DIM 15
#define FOOD_DIM 5
#define MAP_WIDTH 28
#define MAP_HEIGHT 31
#define TILE_DIM 20
#define WINDOW_WIDTH (MAP_WIDTH * TILE_DIM + 200)
#define WINDOW_HEIGHT (MAP_HEIGHT * TILE_DIM)
