name: build-fakeman2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Splashkit Manager
        run: bash <(curl -s https://raw.githubusercontent.com/splashkit/skm/master/install-scripts/skm-install.sh)

      - name: Install Splashkit
        run: ~/.splashkit/skm linux install

      - name: Build FakeMan2
        run: ~/.splashkit/skm clang++ ./FakeMan2/*.cpp -o FakeMan2.exe
