name: build-fakeman2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install splashkit
        run: bash <(curl -s https://raw.githubusercontent.com/splashkit/skm/master/install-scripts/skm-install.sh)

      - name: Reload environment variables
        run: bash

      - name: Build Fakeman2
        run: skm clang++ ./FakeMan2/*.cpp -o .
