name: build-fakeman2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install splashkit
        run: bash <(curl -s https://raw.githubusercontent.com/splashkit/skm/master/install-scripts/skm-install.sh)

      - name: Investigating file structure
        run: | 
        	ls /home/runner/work/FakeMan2
        	ls /home/runner/work/FakeMan2/FakeMan2

      - name: Build Fakeman2
        run: sudo /home/runner/work/FakeMan2/FakeMan2/build.sh
        shell: bash
