name: Slack push notification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: team_he_she_it
        SLACK_COLOR: '#3278BD'
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_TITLE: Message
        SLACK_USERNAME: pushBot
        SLACK_WEBHOOK: 'https://hooks.slack.com/services/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'
